name: Codespell

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check spelling
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout wolfSSH
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: .git,./ide,./keys,./certs,./m4,*.der,*.pem,*.pub
          ignore_words_list: inout,keypair,nd,parm,ser,rcv,inh,bu,fo,te,ans,pendin,anormal,dne
